# Creating a distance matrix
In this notebook you will learn how to work with fasta files and generate a distance matrix that you will need to construct your phylogenetic tree.

Import numpy:

In [2]:
import numpy as np

We will also need to import SeqIO from the BioPython library:

In [3]:
from Bio import SeqIO

Copy and paste the function from the butterfly Notebook that returns the difference between two sequences:

**You will need to make one change: the function needs to find the shortest sequence and stop the analysis at that nucleotide. You can use the "break" command to stop a for loop.**

In [27]:
seqA = "CTGCG"
seqB = "ATGGCCCC"

def diffNum(seqA,seqB):  
    if len(seqA) <= len(seqB):
        short = seqA
        long = seqB
    else:
        short = seqB
        long = seqA
    num_diff = 0
    for c, i in enumerate(short):
        #print(i)
        if c < len(short):
            if i != long[c]:
                num_diff += 1
        else:
            break
    return num_diff

print(diffNum(seqA, seqB))

3


Create an empty list and use the SeqIO.parse() function to append each sequence in the fasta file:

In [5]:
from Bio import SeqIO
seqs = []
for seq_record in list(SeqIO.parse('hemoglobin_sequences.fasta', 'fasta'))[:]:
    seqs.append(seq_record.seq)


Print out the first item in seqs to check that your code worked:

In [6]:
seqs

[Seq('ATGGTGCACCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAG...TAA', SingleLetterAlphabet()),
 Seq('ATGGTCCATTGGACAGCTGAAGAGAAGGCCGCCATCACTTCTGTATGGCAGAAG...TAA', SingleLetterAlphabet()),
 Seq('ATGGTTGAGTGGACAGATGCCGAGCGCACAGCCATCCTTGGCCTGTGGGGAAAG...TAG', SingleLetterAlphabet()),
 Seq('ATGGTGCACCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAG...AAG', SingleLetterAlphabet()),
 Seq('ATGGTTGAGTTGACAGAAGCCCAGCGTGGTGCTATCGTTAACCTGTGGGGACAT...ATA', SingleLetterAlphabet()),
 Seq('ATGGTGCACTGGACTGCTGAGGAGAAGCAGCTCATCACCGGCCTCTGGGGCAAG...TAA', SingleLetterAlphabet()),
 Seq('ATGGTGCACCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAG...AGG', SingleLetterAlphabet()),
 Seq('ATGGTGAATCTGACTGCTGCTGAGAAGACACAAGTCACCAACCTGTGGGGCAAG...TGA', SingleLetterAlphabet()),
 Seq('ATGGTGCATCTGTCTGCTGAGGAGAAGGAGGCCGTCCTCGGCCTGTGGGGCAAA...TAA', SingleLetterAlphabet()),
 Seq('ATGGTGCACCTGACTGATGCTGAGAAGGCTGCTGTCTCTGGCCTGTGGGGAAAG...TAA', SingleLetterAlphabet()),
 Seq('ATGGTGCATCTGACTCCTGAGGAGAAGAATGCCGTCACCACCCTGTGGGGCAAG

Print out just the sequence from the first species using the .seq method:

In [7]:
seqs[0]

Seq('ATGGTGCACCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAG...TAA', SingleLetterAlphabet())

Print out the length of the seqs list to see how many sequences there are:

In [8]:
len(seqs)

13

Create a function that takes the list of sequences as its only argument and returns a numpy array with the hamming distance of each pair of sequences:

Hint: You will need to create an empty two dimensional numpy array with the same number of rows and columns as there are sequences in your list.

In [24]:
empty = np.empty([13,13])
def array(seqs):
    for i in range(len(seqs)):
        for j in range(len(seqs)):
            x = diffNum(seqs[i],seqs[j])
            empty[i,j] = x
    return empty

Run your function:

In [25]:
my_array = array(seqs)

In [26]:
print(my_array)

[[  0. 168. 195.   3. 302. 114.   0.  75.  70.  79.  22. 155.   8.]
 [168.   0. 213. 138. 313. 166. 114. 179. 169. 170. 166. 198. 170.]
 [195. 213.   0. 138. 299. 185. 110. 202. 201. 183. 199. 215. 198.]
 [  3. 138. 138.   0. 247.  94.   1.  62.  60.  63.  18. 122.   4.]
 [302. 313. 299. 247.   0. 311. 209. 310. 303. 304. 301. 324. 299.]
 [114. 166. 185.  94. 311.   0.  77. 117. 115. 127. 114. 125. 115.]
 [  0. 114. 110.   1. 209.  77.   0.  54.  45.  51.  17. 104.   3.]
 [ 75. 179. 202.  62. 310. 117.  54.   0.  84.  88.  70. 136.  71.]
 [ 70. 169. 201.  60. 303. 115.  45.  84.   0.  89.  65. 147.  66.]
 [ 79. 170. 183.  63. 304. 127.  51.  88.  89.   0.  78. 149.  76.]
 [ 22. 166. 199.  18. 301. 114.  17.  70.  65.  78.   0. 156.  18.]
 [155. 198. 215. 122. 324. 125. 104. 136. 147. 149. 156.   0. 152.]
 [  8. 170. 198.   4. 299. 115.   3.  71.  66.  76.  18. 152.   0.]]


In [30]:
x = my_array
fname = "MolGen_FinalProject_Array.txt"

In [32]:
np.savetxt(fname,x,fmt="%.1f")